services:
  ws_docker:
    container_name: ws_container
    image: gitlab.pal-robotics.com:4567/ci/repo/public-ros4hri-alum-devel:test
    hostname: ws_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    stdin_open: true
    tty: true
