services:
  ws_docker:
    container_name: ws_container
    image: oscarmrz/ros4hri_tutorial
    hostname: ws_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    stdin_open: true
    tty: true
